# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 8.0
          - 8.1

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@master
        with:
          path: src/
